### ISSUE TITLE
Problem in start Using Pro

### ISSUE THREAD

**Issue by monahadibarhaghtalab** [victorkifer/clicker#3]
Hi
while I'm trying to upgrade my android version to pro, an error occurred , 
the error said: "An error occurred while processing your request".
what can I do with that?
Thanks

**Comment by victorkifer** [comment]
Hi,
please make sure you have the latest version of Google Play Services installed on your phone.
Also please review this article from Google Play
https://support.google.com/googleplay/answer/1267137?co=GENIE.Platform%3DAndroid&hl=en
